spring:
  application:
    name: comic_reader_backend

  datasource:
    url: ${COMIC_DATABASE_URL}
    username: ${COMIC_DATABASE_USERNAME}
    password: ${COMIC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#    show-sql: true

web:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
  jwt-secret-key: ${JWT_SECRET_KEY}
database:
  storage-url: ${COMIC_OBJECT_STORAGE_URL}
