spring:
  application:
    name: comic_reader_backend

  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: 12355
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

web:
  cors:
    allowed-origins: "http://localhost:5173"
  jwt-secret-key: "SGVsbG9UaGlzSXNDb21pY1JlYWRlcldlYnNpdGVNYWRlV2l0aExvdmVCeUthcnRoaWtleWFuQW5kVGhpc0lzVXNlZFRvU2lnblRoZUhhc2hPZkpXVA=="
database:
  storage-url: "https://vnqpkstmadacbnlcvgax.supabase.co/storage/v1/object/public/comic-asia/"